[project]
name = "wiki-arena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.51.0",
    "mcp[cli]>=1.9.0",
    "openai>=1.79.0",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "wikipedia-api>=0.8.1",
]
