[project]
name = "wiki-arena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.0",
    "anthropic>=0.51.0",
    "fastapi>=0.115.12",
    "mcp[cli]>=1.9.0",
    "openai>=1.79.0",
    "pytest>=8.3.5",
    "python-multipart>=0.0.20",
    "requests>=2.32.3",
    "uvicorn[standard]>=0.34.2",
    "websockets==11.0.3",
    "wikipedia-api>=0.8.1",
]
